#!/usr/bin/env python3
"""Interactive setup for D0mmy API keys. Writes or updates .env in the project root."""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = ROOT / ".env"

FIELDS = [
    {
        "key": "GOOGLE_API_KEY",
        "label": "Google AI API key (Gemini + Gemma + Embeddings)",
        "hint": "Get one at https://aistudio.google.com/app/apikey",
        "required": True,
        "secret": True,
    },
    {
        "key": "HEAVY_MODEL",
        "label": "Heavy model ID (Gemini 3.1 Pro)",
        "hint": "Google AI model ID for architecture/synthesis tasks",
        "required": False,
        "default": "gemini-3.1-pro-preview",
        "secret": False,
    },
    {
        "key": "WORKER_MODEL",
        "label": "Worker model ID (Gemma 4 31B)",
        "hint": "Google AI model ID for parallel worker agents",
        "required": False,
        "default": "gemma-4-31b-it",
        "secret": False,
    },
    {
        "key": "DAEMON_MODEL",
        "label": "Daemon model ID (Gemma 4 26B MoE)",
        "hint": "Google AI model ID for routing and truncation (~4B active params)",
        "required": False,
        "default": "gemma-4-26b-a4b-it",
        "secret": False,
    },
    {
        "key": "EMBEDDING_MODEL",
        "label": "Embedding model ID",
        "hint": "Google AI embedding model",
        "required": False,
        "default": "gemini-embedding-001",
        "secret": False,
    },
    {
        "key": "BACKEND_PORT",
        "label": "FastAPI backend port",
        "required": False,
        "default": "8000",
        "secret": False,
    },
    {
        "key": "CHROMA_PERSIST_DIR",
        "label": "ChromaDB persistence directory",
        "required": False,
        "default": "./data/chroma",
        "secret": False,
    },
]


def load_existing() -> dict[str, str]:
    if not ENV_FILE.exists():
        return {}
    pairs: dict[str, str] = {}
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            pairs[k.strip()] = v.strip()
    return pairs


def mask(value: str) -> str:
    if len(value) <= 8:
        return "*" * len(value)
    return value[:4] + "*" * (len(value) - 8) + value[-4:]


def prompt_field(field: dict, existing: dict[str, str]) -> str:
    key = field["key"]
    current = existing.get(key, "")
    default = field.get("default", current)
    hint = field.get("hint", "")
    is_secret = field["secret"]
    is_required = field["required"]

    print(f"\n  {field['label']}")
    if hint:
        print(f"  {hint}")
    if current:
        display = mask(current) if is_secret else current
        print(f"  Current: {display}")

    suffix = " (required): " if is_required else f" [{default or 'skip'}]: "
    try:
        raw = input(f"  → {key}{suffix}").strip()
    except (KeyboardInterrupt, EOFError):
        print("\nAborted.")
        sys.exit(0)

    if not raw:
        if current:
            return current
        if default and not is_required:
            return default
        if is_required:
            print("  This field is required.")
            return prompt_field(field, existing)
    return raw


def write_env(values: dict[str, str]) -> None:
    lines = ["# D0mmy — generated by scripts/setup_keys.py\n"]
    for field in FIELDS:
        k = field["key"]
        v = values.get(k, field.get("default", ""))
        lines.append(f"{k}={v}\n")
    ENV_FILE.write_text("".join(lines))


def main() -> None:
    print("\n╔══════════════════════════════════════╗")
    print("║   D0mmy — API Key Setup              ║")
    print("╚══════════════════════════════════════╝")
    print(f"\n  All AI calls (Gemini + Gemma + Embeddings) use a single Google API key.")
    print(f"  Writing to: {ENV_FILE}")

    existing = load_existing()
    values: dict[str, str] = {}

    for field in FIELDS:
        values[field["key"]] = prompt_field(field, existing)

    write_env(values)
    print(f"\n  Saved to {ENV_FILE}")

    missing = [f["key"] for f in FIELDS if f["required"] and not values.get(f["key"])]
    if missing:
        print(f"\n  WARNING: Required fields missing: {', '.join(missing)}")
        sys.exit(1)
    else:
        print("  Ready. Run: uvicorn backend.main:app --reload\n")


if __name__ == "__main__":
    main()
